### ISSUE TITLE
SBC with collaborative nested sampling

### ISSUE THREAD

**Issue by JohannesBuchner** [seantalts/simulation-based-calibration#1]
Dear Sean,

I have been working on a modification of nested sampling that allows analysing multiple data sets simultaneously. The benefit is that it can re-use model predictions, especially beneficial when using slow, numerical models and relatively similar datasets. There may be some overlap with SBC worth pondering about.

The paper is at https://arxiv.org/abs/1707.04476 and there is demo code at https://github.com/JohannesBuchner/massivedatans/tree/musefuse

Thanks,
Johannes

**Comment by seantalts** [comment]
Interesting! I'll take a look, thanks. I also have email with my username at gmail.com if you prefer a more direct connection or to talk about research ideas.
